// GET ALL MOVIE
export const LOADING_GET_ALL_MOVIE = "LOADING_GET_ALL_MOVIE";
export const SUCCESS_GET_ALL_MOVIE = "SUCCESS_GET_ALL_MOVIE";
export const FAILED_GET_ALL_MOVIE = "FAILED_GET_ALL_MOVIE";
