// GET ALL CATEGORY
export const LOADING_GET_ALL_CATEGORY_MOVIE = "LOADING_GET_ALL_CATEGORY_MOVIE";
export const SUCCESS_GET_ALL_CATEGORY_MOVIE = "SUCCESS_GET_ALL_CATEGORY_MOVIE";
export const FAILED_GET_ALL_CATEGORY_MOVIE = "FAILED_GET_ALL_CATEGORY_MOVIE";
