// GET DETAIL MOVIE
export const LOADING_GET_DETAIL_MOVIE = "LOADING_GET_DETAIL_MOVIE";
export const SUCCESS_GET_DETAIL_MOVIE = "SUCCESS_GET_DETAIL_MOVIE";
export const FAILED_GET_DETAIL_MOVIE = "FAILED_GET_DETAIL_MOVIE";
